# Generated by Django 5.2 on 2025-05-31 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0001_initial'),
        ('institution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='curriculum_track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='institution.curriculumtrack'),
        ),
        migrations.AddField(
            model_name='exam',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='institution.section'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='institution.subject'),
        ),
        migrations.AddField(
            model_name='exammark',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='exam.exam'),
        ),
        migrations.AddField(
            model_name='exammark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_marks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['curriculum_track', 'section', 'subject'], name='exam_exam_curricu_bfcfba_idx'),
        ),
        migrations.AddIndex(
            model_name='exammark',
            index=models.Index(fields=['exam', 'student'], name='exam_examma_exam_id_31db2d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exammark',
            unique_together={('exam', 'student')},
        ),
    ]
