# Generated by Django 5.2 on 2025-05-31 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 6, 4, 56, 167121, tzinfo=datetime.timezone.utc)),
        ),
    ]
