# Generated by Django 5.2 on 2025-06-01 03:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_invitation_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 8, 3, 26, 34, 373324, tzinfo=datetime.timezone.utc)),
        ),
    ]
