# Generated by Django 5.2 on 2025-05-31 06:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BkashPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('scholarship_applied', models.BooleanField(default=False)),
                ('scholarship_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bkash_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='payment_management.bkashpayment')),
                ('student_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='institution.studentenrollment')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionPaymentTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_disbursed', models.BooleanField(default=False)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_trackers', to='institution.institutioninfo')),
                ('student_fee_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_trackers', to='payment_management.studentfeepayment')),
            ],
        ),
    ]
