# Generated by Django 5.2 on 2025-05-31 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0002_initial'),
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='globalquizquestion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='globalquizquestion',
            name='curriculum_track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions_curriculum_track', to='institution.globalcurriculumtrack'),
        ),
        migrations.AddField(
            model_name='globalquizquestion',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions_lesson', to='institution.globallesson'),
        ),
        migrations.AddField(
            model_name='globalquizquestion',
            name='micro_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions_micro_lesson', to='institution.globalmicrolesson'),
        ),
        migrations.AddField(
            model_name='globalquizquestion',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions_module', to='institution.globalmodule'),
        ),
        migrations.AddField(
            model_name='globalquizquestion',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions_stream', to='institution.globalstream'),
        ),
        migrations.AddField(
            model_name='globalquizquestion',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions_subject', to='institution.globalsubject'),
        ),
        migrations.AddField(
            model_name='globalquizquestion',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions_unit', to='institution.globalunit'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizcontainer',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizcontainer',
            name='curriculum_track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_container_curriculum_track', to='institution.curriculumtrack'),
        ),
        migrations.AddField(
            model_name='quizcontainer',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_container_lesson', to='institution.lesson'),
        ),
        migrations.AddField(
            model_name='quizcontainer',
            name='micro_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_container_micro_lesson', to='institution.microlesson'),
        ),
        migrations.AddField(
            model_name='quizcontainer',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_container_module', to='institution.module'),
        ),
        migrations.AddField(
            model_name='quizcontainer',
            name='questions',
            field=models.ManyToManyField(related_name='quiz_containers', to='quiz.globalquizquestion'),
        ),
        migrations.AddField(
            model_name='quizcontainer',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_container_section', to='institution.section'),
        ),
        migrations.AddField(
            model_name='quizcontainer',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_container_stream', to='institution.stream'),
        ),
        migrations.AddField(
            model_name='quizcontainer',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_container_subject', to='institution.subject'),
        ),
        migrations.AddField(
            model_name='quizcontainer',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_container_unit', to='institution.unit'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.quizcontainer'),
        ),
        migrations.AddField(
            model_name='quizoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.globalquizquestion'),
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quiz.quizattempt'),
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quiz.globalquizquestion'),
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.quizoption'),
        ),
        migrations.AlterUniqueTogether(
            name='quizoption',
            unique_together={('question', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='quizresponse',
            unique_together={('attempt', 'question')},
        ),
    ]
