# Generated by Django 5.2 on 2025-05-31 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0002_initial'),
        ('syllabus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_syllabi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='curriculum_track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='institution.curriculumtrack'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='institution.institutioninfo'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='syllabi', to='institution.lesson'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='micro_lessons',
            field=models.ManyToManyField(blank=True, related_name='syllabi', to='institution.microlesson'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='syllabi', to='institution.module'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='institution.section'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='institution.subject'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='units',
            field=models.ManyToManyField(blank=True, related_name='syllabi', to='institution.unit'),
        ),
        migrations.AddIndex(
            model_name='syllabus',
            index=models.Index(fields=['institution', 'curriculum_track', 'section', 'subject'], name='syllabus_sy_institu_4d9708_idx'),
        ),
    ]
