# Generated by Django 5.2 on 2025-05-31 06:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, help_text='Content of the notice', null=True)),
                ('target_audience', models.CharField(choices=[('students', 'Students'), ('teachers', 'Teachers'), ('parents', 'Parents'), ('all', 'All')], default='all', help_text='Target audience for the notice', max_length=20)),
                ('notice_type', models.CharField(choices=[('general', 'General'), ('urgent', 'Urgent'), ('event', 'Event'), ('announcement', 'Announcement'), ('alert', 'Alert')], default='general', help_text='Type of the notice', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Optional image for the notice', null=True, upload_to='notices/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
            },
        ),
    ]
