# Generated by Django 5.2 on 2025-05-31 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0002_initial'),
        ('notice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notice',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='institution.institutioninfo'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['institution', 'created_at'], name='notice_noti_institu_3817ea_idx'),
        ),
    ]
