# Generated by Django 5.2 on 2025-05-31 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='institutioninfo',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institutionfee',
            name='institution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='default_fee', to='institution.institutioninfo'),
        ),
        migrations.AddField(
            model_name='curriculumtrack',
            name='institution_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_curriculum_tracks', to='institution.institutioninfo'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='institution.globallesson'),
        ),
        migrations.AddField(
            model_name='microlesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='micro_lessons', to='institution.lesson'),
        ),
        migrations.AddField(
            model_name='microlesson',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='micro_lessons', to='institution.globalmicrolesson'),
        ),
        migrations.AddField(
            model_name='module',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='institution.globalmodule'),
        ),
        migrations.AddField(
            model_name='section',
            name='curriculum_track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='institution.curriculumtrack'),
        ),
        migrations.AddField(
            model_name='stream',
            name='curriculum_track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='institution.curriculumtrack'),
        ),
        migrations.AddField(
            model_name='stream',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_streams', to='institution.globalstream'),
        ),
        migrations.AddField(
            model_name='stream',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='institution.section'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='curriculum_track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='institution.curriculumtrack'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='institution.institutioninfo'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='institution.section'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='student_enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee', to='institution.studentenrollment'),
        ),
        migrations.AddField(
            model_name='subject',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='institution.globalsubject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='institution.stream'),
        ),
        migrations.AddField(
            model_name='module',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='institution.subject'),
        ),
        migrations.AddField(
            model_name='teacherenrollment',
            name='curriculum_track',
            field=models.ManyToManyField(related_name='teacher_enrollments', to='institution.curriculumtrack'),
        ),
        migrations.AddField(
            model_name='teacherenrollment',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_enrollments', to='institution.institutioninfo'),
        ),
        migrations.AddField(
            model_name='teacherenrollment',
            name='section',
            field=models.ManyToManyField(blank=True, related_name='teacher_enrollments', to='institution.section'),
        ),
        migrations.AddField(
            model_name='teacherenrollment',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teacher_enrollments', to='institution.subject'),
        ),
        migrations.AddField(
            model_name='teacherenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unit',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='institution.module'),
        ),
        migrations.AddField(
            model_name='unit',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='institution.globalunit'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='institution.unit'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('curriculum_track', 'name')},
        ),
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['user', 'curriculum_track', 'section'], name='institution_user_id_20f772_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together={('user', 'curriculum_track', 'section')},
        ),
    ]
